### ISSUE TITLE
English translation?

### ISSUE THREAD

**Issue by ljudva** [peppelinux/Ansible-Shibboleth-IDP-SP-Debian#10]
Hi, 

thank you for your hard work with this. Shibboleth is a complex beast.

If this built is too complex for some, I've provided the VM with my approach:

https://github.com/onelogin/python3-saml/issues/202

Thanks

Ciao

**Comment by peppelinux** [comment]
Hi, thank you.
Consider to put a star to this project and cite It in your onelogin issue, I'll be very thankful for this.
I'm wondering to translate the readme from long time, I'd start sooner or later. Thank you for reminder

**Comment by ljudva** [comment]
No worries. It is already mentioned there.

Testing your procedure now. Will let you know of any issues.
