### ISSUE TITLE
github private repo?

### ISSUE THREAD

**Issue by ljudva** [peppelinux/Ansible-Shibboleth-IDP-SP-Debian#12]
Hi again, 

this looks like a private repo:

debian:~# git clone https://github.com/ConsortiumGARR/Ansible-Shibboleth-IDP-SP-Debian
Cloning into 'Ansible-Shibboleth-IDP-SP-Debian'...
Username for 'https://github.com': ^C

Please confirm.

Thanks

**Comment by peppelinux** [comment]
Yes, you should use this:
https://github.com/peppelinux/Ansible-Shibboleth-IDP-SP-Debian

I'm going to fix it

**Comment by peppelinux** [comment]
fixed here:
https://github.com/peppelinux/Ansible-Shibboleth-IDP-SP-Debian/commit/73cf3dfb1f8d00981297dede7a70347f688c04bd
