### ISSUE TITLE
Excellent work!

### ISSUE THREAD

**Issue by ljudva** [peppelinux/Ansible-Shibboleth-IDP-SP-Debian#13]
Hi Giuseppe,

excellent work! There are a number of changes for VirtualBox to work but I got there. 

020-07-22 00:08:18,267 - 10.0.2.2 - INFO [org.ldaptive.auth.Authenticator:291] - Authentication succeeded for dn: uid=gino,ou=people,dc=testunical,dc=it

![idpIT01](https://user-images.githubusercontent.com/36252744/88145677-62b75c80-cc2d-11ea-9e69-b46b1afd1dc2.png)

After this, getting opensaml::FatalProfileException at (https://sp.testunical.it:4443/Shibboleth.sso/SAML2/POST) 

Unable to establish security of incoming assertion.

Can we not sign the assertion or something? I'm not familiar with Apache Shib module.

Any ideas?

Here is the metadata:
```
debian:/home/jampy# grep --color -R "https://idp.testunical.it:444" /etc/shibboleth/*
/etc/shibboleth/metadata/idp.testunical.it-metadata.xml:<EntityDescriptor  xmlns="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:shibmd="urn:mace:shibboleth:metadata:1.0" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:mdui="urn:oasis:names:tc:SAML:metadata:ui" xmlns:req-attr="urn:oasis:names:tc:SAML:protocol:ext:req-attr"  entityID="https://idp.testunical.it:4443/idp/shibboleth">
/etc/shibboleth/metadata/idp.testunical.it-metadata.xml:                <mdui:Logo height="80" width="80">https://idp.testunical.it:4443/Path/To/Logo.png</mdui:Logo>
/etc/shibboleth/metadata/idp.testunical.it-metadata.xml:        <SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://idp.testunical.it:4443/idp/profile/SAML2/POST/SLO"/>
/etc/shibboleth/metadata/idp.testunical.it-metadata.xml:        <SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST-SimpleSign" Location="https://idp.testunical.it:4443/idp/profile/SAML2/POST-SimpleSign/SLO"/>
/etc/shibboleth/metadata/idp.testunical.it-metadata.xml:        <SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://idp.testunical.it:4443/idp/profile/SAML2/Redirect/SLO"/>
/etc/shibboleth/metadata/idp.testunical.it-metadata.xml:        <SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://idp.testunical.it:4443/idp/profile/SAML2/SOAP/SLO"/>
/etc/shibboleth/metadata/idp.testunical.it-metadata.xml: <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST-SimpleSign" req-attr:supportsRequestedAttributes="true" Location="https://idp.testunical.it:4443/idp/profile/SAML2/POST-SimpleSign/SSO"/>
/etc/shibboleth/metadata/idp.testunical.it-metadata.xml:        <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" req-attr:supportsRequestedAttributes="true" Location="https://idp.testunical.it:4443/idp/profile/SAML2/Redirect/SSO"/>
/etc/shibboleth/metadata/idp.testunical.it-metadata.xml:        <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" req-attr:supportsRequestedAttributes="true" Location="https://idp.testunical.it:4443/idp/profile/SAML2/POST/SSO"/>
/etc/shibboleth/metadata/idp.testunical.it-metadata.xml:        <AttributeService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://idp.testunical.it:4443/idp/profile/SAML2/SOAP/AttributeQuery"/>
/etc/shibboleth/shibboleth2.xml:                              entityID="https://idp.testunical.it:4443/idp/shibboleth">
```
And the log:
```
2020-07-21 23:47:13 WARN Shibboleth.SessionInitiator.SAML2 [8] [default]: unable to locate metadata for provider (https://idp.testunical.it:4443/idp/shibboleth)
2020-07-22 00:11:00 WARN OpenSAML.MessageDecoder.SAML2 [11] [default]: no metadata found, can't establish identity of issuer (https://idp.testunical.it/idp/shibboleth)
2020-07-22 00:11:00 WARN Shibboleth.SSO.SAML2 [11] [default]: no metadata found, can't establish identity of issuer (https://idp.testunical.it/idp/shibboleth)
2020-07-22 00:11:00 WARN Shibboleth.SSO.SAML2 [11] [default]: detected a problem with assertion: Unable to establish security of incoming assertion.
```

Not sure why is using https://idp.testunical.it/idp/shibboleth for identity when accessed by https://idp.testunical.it:4443/idp/shibboleth

Thanks
Cheers

**Comment by peppelinux** [comment]
The port :4443 would be the problem, see /etc/shibboleth/shibboleth.xml, the entity id used for the idp it's there. Does it have that port in it?

I put a troubleshooting with these elements, see:
https://github.com/peppelinux/Ansible-Shibboleth-IDP-SP-Debian#fatalprofileexception-sp

**Comment by ljudva** [comment]
Updated the above, not sure if you've seen it...
/etc/shibboleth/shibboleth2.xml:                              entityID="https://idp.testunical.it:4443/idp/shibboleth">

This works now though:

https://idp.testunical.it:4443/idp/profile/admin/resolvertest?requester=https://sp.testunical.it:4443/shibboleth&principal=gino

```
{
"requester": "https://sp.testunical.it:4443/shibboleth",
"principal": "gino",
"attributes": [


  {
    "name": "givenName",
    "values": [
        "gino"
    ]
  },
  

  {
    "name": "schacHomeOrganizationType",
    "values": [
        "urn:schac:homeOrganizationType:eu:higherEducationalInstitution"
    ]
  },
  

  {
    "name": "schacPersonalUniqueID",
    "values": [
        "urn:schac:personalUniqueID:it:CF:CODICEFISCALEgino"
    ]
  },
  

  {
    "name": "eduPersonAffiliation",
    "values": [
        "affiliate"
    ]
  },
  

  {
    "name": "eduPersonEntitlement",
    "values": [
        "urn:mace:dir:entitlement:common-lib-terms"
    ]
  },
  

  {
    "name": "email",
    "values": [
        "gino.grossi@testunical.it"
    ]
  },
  

  {
    "name": "sn",
    "values": [
        "rossi"
    ]
  },
  

  {
    "name": "title",
    "values": [
        "ospite"
    ]
  },
  

  {
    "name": "schacPersonalUniqueCode",
    "values": [
        "urn:schac:personalUniqueCode:it:testunical.it:dipendente:15432",
        "urn:schac:personalUniqueCode:it:testunical.it:studente:126145"
    ]
  },
  

  {
    "name": "mail",
    "values": [
        "gino.grossi@testunical.it"
    ]
  },
  

  {
    "name": "eduPersonScopedAffiliation",
    "values": [
        "member@testunical.it",
        "staff@testunical.it"
    ]
  },
  

  {
    "name": "uid",
    "values": [
        "gino"
    ]
  },
  

  {
    "name": "eduPersonPrincipalName",
    "values": [
        "gino@testunical.it"
    ]
  },
  

  {
    "name": "displayName",
    "values": [
        "rossi gino"
    ]
  },
  

  {
    "name": "schacHomeOrganization",
    "values": [
        "testunical.it"
    ]
  },
  

  {
    "name": "cn",
    "values": [
        "gino rossi"
    ]
  }
  

]
}
```

This is also working:
```
debian:/opt/shibboleth-idp/conf# /opt/shibboleth-idp/bin/aacli.sh -n gino -r https://sp.testunical.it:4443/shibboleth --saml2 -u http://localhost:8080/idp
```

I suspect it is SP:

```
This service requires information about you that your identity provider did not release. To gain access to this service, your identity provider must release the required information.
 You were trying to access the following URL:

    https://sp.testunical.it:4443/secure/index.php
```

hmmm....

**Comment by peppelinux** [comment]
Yes, It seems to be sp's attrchecker.
Is there some custom specification in sp configuration regarding the required attributes?

**Comment by ljudva** [comment]
Thanks for reply.

I did try to add into attribute-filter-local... as you did, but does not make any difference. 

Would it help if I send you the VM image? Basically I replaced everything with xxx.it:4443, that's all. And obviously did set Port Forwarding on VirtualBox to host 4443 and guest 443.
Also touched /etc/hosts to reflect 127.0.0.1 for everything.  

Cheers

**Comment by peppelinux** [comment]
I think that you should use samltracer and sniff the saml2 assertions, you should see those release to sp.

That's the place where we filter attributes to SPs:
https://github.com/peppelinux/Ansible-Shibboleth-IDP-SP-Debian/blob/master/roles/shib4idp_configure/templates/attribute-filter-local.xml#L10

please share your playbook.yml for acknoledgement.
Remember to restart shibboleth-idp (or single service) everytime you make modifications to its configuration files.
If you need a working image you just have to use the playbook without any changements

**Comment by ljudva** [comment]
Cool thanks. Did not change playbook tho. Just IP's

Clean VM will not work over VB port forwarding, thats the problem. I think you and me are the only one on the Planet with a knowledge to provide VB image for the developers :)
Django/Flask/Jam.py devs at my Uni need it for research.

**Comment by peppelinux** [comment]
could you use VB bridged interface?
This would avois DNAT and port forwariding. I still didn't understand the problem but hope to gve you the needed help
I am also a django/python programmer, you're welcome

**Comment by ljudva** [comment]
Indeed, that is a possibility.
Yes, I've seen your repos. Would be great to have you on board for http://jam-py.com project. It is way more sophisticated than web2py appadmin from Massimo Di Pierro. 
Grazie
